spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.218:1521:orcl
    username: wj_ehr
    password: 123
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true